In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Book4.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
inputs = df.drop('Survived',axis='columns')

In [ ]:
target = df['Survived']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_PassengerId = LabelEncoder()
le_Pclass = LabelEncoder()
le_Name= LabelEncoder()
le_Sex = LabelEncoder()
le_Age = LabelEncoder()
le_SibSp = LabelEncoder()
le_Parch = LabelEncoder()
le_Ticket = LabelEncoder()
le_Fare = LabelEncoder()
le_Cabin = LabelEncoder()
le_Embarked = LabelEncoder()

In [ ]:
inputs['PassengerId_n'] = le_PassengerId.fit_transform(inputs['PassengerId'])
inputs['Pclass_n'] = le_Pclass.fit_transform(inputs['Pclass'])
inputs['Name_n'] = le_Name.fit_transform(inputs['Name'])
inputs['Sex_n'] = le_Sex.fit_transform(inputs['Sex'])
inputs['Age_n'] = le_Age.fit_transform(inputs['Age'])
inputs['SibSp_n'] = le_SibSp.fit_transform(inputs['SibSp'])
inputs['Parch_n'] = le_Parch.fit_transform(inputs['Parch'])
inputs['Ticket_n'] = le_Ticket.fit_transform(inputs['Ticket'])
inputs['Fare_n'] = le_Fare.fit_transform(inputs['Fare'])
inputs['Cabin_n'] = le_Cabin.fit_transform(inputs['Cabin'])
inputs['Embarked_n'] = le_Embarked.fit_transform(inputs['Embarked'])

In [ ]:
inputs

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,Pclass_n,Name_n,Sex_n,Age_n,SibSp_n,Parch_n,Ticket_n,Fare_n,Cabin_n,Embarked_n
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,...,2,108,1,28,1,0,523,18,147,2
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,...,0,190,0,51,1,0,596,207,81,0
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,...,2,353,0,34,0,0,669,41,147,2
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,...,0,272,0,47,1,0,49,189,55,2
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,...,2,15,1,47,0,0,472,43,147,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,...,1,548,1,35,0,0,101,85,147,2
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,...,0,303,0,24,0,0,14,153,30,2
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,...,2,413,0,88,1,2,675,131,147,2
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,...,0,81,1,34,0,0,8,153,60,0
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,...,2,220,1,42,0,0,466,30,147,1

In [ ]:
inputs_n = inputs.drop(['PassengerId','Pclass','Name','Sex','Age','SibSp','Parch','Ticket','Fare','Cabin','Embarked'],axis='columns')

In [ ]:
inputs_n

,PassengerId_n,Pclass_n,Name_n,Sex_n,Age_n,SibSp_n,Parch_n,Ticket_n,Fare_n,Cabin_n,Embarked_n
0,0,2,108,1,28,1,0,523,18,147,2
1,1,0,190,0,51,1,0,596,207,81,0
2,2,2,353,0,34,0,0,669,41,147,2
3,3,0,272,0,47,1,0,49,189,55,2
4,4,2,15,1,47,0,0,472,43,147,2
...,...,...,...,...,...,...,...,...,...,...,...
886,886,1,548,1,35,0,0,101,85,147,2
887,887,0,303,0,24,0,0,14,153,30,2
888,888,2,413,0,88,1,2,675,131,147,2
889,889,0,81,1,34,0,0,8,153,60,0
890,890,2,220,1,42,0,0,466,30,147,1

In [ ]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [ ]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [ ]:
model.score(inputs_n,target)

1.0

In [ ]:
model.predict([[0, 2, 108, 1, 28, 1, 0, 523, 18, 147, 2]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])